2025-03-13 09:56:27,741 INFO    MainThread:81085 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-13 09:56:27,741 INFO    MainThread:81085 [wandb_setup.py:_flush():67] Configure stats pid to 81085
2025-03-13 09:56:27,741 INFO    MainThread:81085 [wandb_setup.py:_flush():67] Loading settings from /Users/cory/.config/wandb/settings
2025-03-13 09:56:27,741 INFO    MainThread:81085 [wandb_setup.py:_flush():67] Loading settings from /Users/cory/dev/pinecone-field/wandb-weave/wandb/settings
2025-03-13 09:56:27,741 INFO    MainThread:81085 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/cory/dev/pinecone-field/wandb-weave/wandb/run-20250313_095627-e26r6wpq/logs/debug.log
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/cory/dev/pinecone-field/wandb-weave/wandb/run-20250313_095627-e26r6wpq/logs/debug-internal.log
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:init():761] calling init triggers
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'model': 'llama-text-embed-v2', 'index': 'nvidia-blog-embeddings', 'top_k': 10, 'rerank_model': 'cross-encoder/ms-marco-MiniLM-L-6-v2', '_wandb': {}}
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:init():784] starting backend
2025-03-13 09:56:27,742 INFO    MainThread:81085 [wandb_init.py:init():788] sending inform_init request
2025-03-13 09:56:27,779 INFO    MainThread:81085 [wandb_init.py:init():798] backend started and connected
2025-03-13 09:56:27,784 INFO    MainThread:81085 [wandb_init.py:init():891] updated telemetry
2025-03-13 09:56:27,819 INFO    MainThread:81085 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-13 09:56:27,944 ERROR   MainThread:81085 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/Users/cory/dev/pinecone-field/wandb-weave/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cory/dev/pinecone-field/wandb-weave/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403: {"data":{"upsertBucket":null},"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
2025-03-13 09:57:57,029 INFO    MsgRouterThr:81085 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
